---
- name: Jenkins Node
  hosts: slave
  remote_user: ubuntu
  become: true

  tasks:
    - name: Update Server and install Java JDK
      shell: |
        apt update && apt -y upgrade
        apt install -y --no-install-recommends openjdk-17-jdk-headless

    - name: Add Docker's official GPG key
      shell: |
        apt-get install ca-certificates curl
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
    
    - name: Add the repository to Apt sources
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update

    - name: Install Docker
      shell: apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    - name: Add Jenkins User
      shell: |
        mkdir /home/jenkins
        chown -R ubuntu /home/jenkins
        usermod -aG docker ubuntu
    
    - name: Make Jenkins Agent Service directory
      shell: |
        mkdir -p /usr/local/jenkins-service
        chown ubuntu /usr/local/jenkins-service
    
    - name: Copy agent command
      copy:
        src: ./start-agent.sh
        dest: /usr/local/jenkins-service/start-agent.sh
        mode: +x
    
    - name: Create Service file in System
      copy:
        src: ./jenkins-agent.service
        dest: /etc/systemd/system/jenkins-agent.service
    
    - name: Start Jenkins Agent Service
      shell: |
        systemctl enable jenkins-agent.service
        systemctl start jenkins-agent.service